---
30Gi:
    markers:
        gbsl.gym30: 0
    mappings:
        - section: /index.mdx
          material: /Structure/klassen/30Gi/index.mdx
        - section: /einzellektion.json
          material: /Structure/klassen/30Gi/einzellektion.json
        - section: /praktikum.json
          material: /Structure/klassen/30Gi/praktikum.json
        - section: 01-Onboarding
          material: Onboarding-2025
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-Computer-Hacks
          material: Computer-Hacks
        - section: 04-Programmieren
          material: Programmieren-2026

29Gn:
    markers:
        gbsl.gym29: 0
    mappings:
        - section: /index.mdx
          material: /Structure/klassen/29Gn/index.mdx
        - section: /einzellektion.json
          material: /Structure/klassen/29Gn/einzellektion.json
        - section: /praktikum.json
          material: /Structure/klassen/29Gn/praktikum.json
        - section: /termine_fs26.json
          material: /Structure/klassen/29Gn/termine_fs26.json
        - section: /termine_hs26.json
          material: /Structure/klassen/29Gn/termine_hs26.json
        - section: 01-Onboarding
          material: Onboarding-2025
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics-2025
        - section: 04-Programmieren
          material: Programmieren-2025
        - section: 05-IN-Biber-2025
          material: IN-Biber/2025
        - section: 06-SOL-Text-Adventure
          material: SOL-Text-Adventure
        # - section: 07-Probe-Turtle-2
        #   material: tw_confidential-material/Probe-Turtle-2-GYM29-29Gn
        - section: 08-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 09-Information-Daten
          material: Information-Daten
        # - section: 08-Repetition-IN-GYM1/index.mdx
        #   material: Repetition-2025/Repetition-GYM28-Kurz.mdx
29Gd:
    markers:
        gbsl.gym29: 0
    mappings:
        - section: /index.mdx
          material: /Structure/klassen/29Gd/index.mdx
        - section: /einzellektion.json
          material: /Structure/klassen/29Gd/einzellektion.json
        - section: /praktikum.json
          material: /Structure/klassen/29Gd/praktikum.json
        - section: /termine_hs25.json
          material: /Structure/klassen/29Gd/termine_hs25.json
        - section: /termine_hs26.json
          material: /Structure/klassen/29Gd/termine_hs26.json
        - section: 01-Onboarding
          material: Onboarding-2025
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics-2025
        - section: 04-Programmieren
          material: Programmieren-2025
        - section: 05-IN-Biber-2025
          material: IN-Biber/2025
        - section: 06-SOL-Text-Adventure
          material: SOL-Text-Adventure
        # - section: 07-Probe-Turtle-2
        #   material: tw_confidential-material/Probe-Turtle-2-GYM29-29Gd
        - section: 08-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 09-Information-Daten
          material: Information-Daten