---
29Gn:
    markers:
        gym.29Gn: 0
    mappings:
        - section: /index.mdx
          material: /Structure/klassen/29Gn/index.mdx
        - section: /einzellektion.json
          material: /Structure/klassen/29Gn/einzellektion.json
        - section: /praktikum.json
          material: /Structure/klassen/29Gn/praktikum.json
        - section: 01-Onboarding
          material: Onboarding-2024
        - section: 02-Erste-Hilfe
          material: Erste-Hilfe
        - section: 03-BYOD-Basics
          material: BYOD-Basics
        - section: 04-Programmieren-1
          material: Programmieren-1
        - section: 05-IN-Biber-2024
          material: IN-Biber/2024
        - section: 06-Information-Daten
          material: Information-Daten
        - section: 07-Textverarbeitung-und-Style
          material: Textverarbeitung-Style
        - section: 08-Repetition-IN-GYM1/index.mdx
          material: Repetition-2025/Repetition-GYM28-Kurz.mdx
